sudo: required
services: 
  - docker

  before_install:
    - docker build -t dani888/react-test -f ./client/Dockerfile.dev ./client

  script: 
    - docker run dani888/react-test npm test -- --coverage

  after_success:
    - docker build -t dani888/multi-client ./client
    - docker build -t dani888/multi-server ./server
    - docker build -t dani888/multi-nginx ./nginx
    - docker build -t dani888/multi-worker ./worker

    script:
  - docker run -e CI=true USERNAME/react-test npm test